---
swagger: "2.0"
info:
  description: "Article API"
  version: "1.0.0"
  title: "Article API"
host: "article-aggregate"
basePath: "/"
schemes:
- "http"
produces:
- "application/json"
paths:
  /v1/articles/recent/{limit}:
    get:
      x-swagger-router-controller: articles
      description: Gets recent articles.
      operationId: getRecent
      parameters:
        - name: limit
          in: path
          description: limit of articles you want
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: got articles
          schema:
            $ref: '#/definitions/articles'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  articles:
    type: array
    items:
      $ref: '#/definitions/article'
  article:
    type: object
    required:
      - title
    properties:
      title:
        type: string
  errorModel:
    type: object
    required:
      - message
    properties:
      message:
        type: string
